// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kaizenbackend.Data;

#nullable disable

namespace kaizenbackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326173846_UpdateClientProfile")]
    partial class UpdateClientProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kaizenbackend.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("kaizenbackend.Models.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnoses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KnownTriggers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PreviousTherapy")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("kaizenbackend.Models.ProfessionalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfessionalProfiles");
                });

            modelBuilder.Entity("kaizenbackend.Models.SelfAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnxietyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AnxietyScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepressionLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DepressionScore")
                        .HasColumnType("double precision");

                    b.Property<string>("LonelinessLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LonelinessScore")
                        .HasColumnType("double precision");

                    b.Property<string>("OverallLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Primaryconcern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Q1")
                        .HasColumnType("integer");

                    b.Property<int>("Q10")
                        .HasColumnType("integer");

                    b.Property<int>("Q11")
                        .HasColumnType("integer");

                    b.Property<int>("Q12")
                        .HasColumnType("integer");

                    b.Property<int>("Q13")
                        .HasColumnType("integer");

                    b.Property<int>("Q14")
                        .HasColumnType("integer");

                    b.Property<int>("Q15")
                        .HasColumnType("integer");

                    b.Property<int>("Q2")
                        .HasColumnType("integer");

                    b.Property<int>("Q3")
                        .HasColumnType("integer");

                    b.Property<int>("Q4")
                        .HasColumnType("integer");

                    b.Property<int>("Q5")
                        .HasColumnType("integer");

                    b.Property<int>("Q6")
                        .HasColumnType("integer");

                    b.Property<int>("Q7")
                        .HasColumnType("integer");

                    b.Property<int>("Q8")
                        .HasColumnType("integer");

                    b.Property<int>("Q9")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SelfAssessments");
                });

            modelBuilder.Entity("kaizenbackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("kaizenbackend.Models.Admin", b =>
                {
                    b.HasOne("kaizenbackend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("kaizenbackend.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaizenbackend.Models.ClientProfile", b =>
                {
                    b.HasOne("kaizenbackend.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("kaizenbackend.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaizenbackend.Models.ProfessionalProfile", b =>
                {
                    b.HasOne("kaizenbackend.Models.User", "User")
                        .WithOne("ProfessionalProfile")
                        .HasForeignKey("kaizenbackend.Models.ProfessionalProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaizenbackend.Models.SelfAssessment", b =>
                {
                    b.HasOne("kaizenbackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("kaizenbackend.Models.User", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("ProfessionalProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
