const BRAND_PINK = [233, 30, 140];
const BRAND_PURPLE = [156, 39, 176];
const MUTED_TEXT = [100, 100, 100];

export const getReportGeneratorName = () => {
  const storedFullName = localStorage.getItem('fullName') || '';
  const firstName = localStorage.getItem('firstName') || '';
  const lastName = localStorage.getItem('lastName') || '';
  return storedFullName.trim() || `${firstName} ${lastName}`.trim() || 'User';
};

export const addReportHeader = (doc, title, details = []) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;
  const generatorName = getReportGeneratorName();
  const reportTitle = !title.includes(` for ${generatorName}`)
    ? `${title} for ${generatorName}`
    : title;
  const reportDetails = [
    `Generated by: ${generatorName}`,
    ...details.filter(Boolean)
  ];

  doc.setFont('times', 'bolditalic');
  doc.setFontSize(24);
  doc.setTextColor(...BRAND_PINK);
  doc.text('Kaizen Mental Health Platform', centerX, 18, { align: 'center' });

  doc.setDrawColor(...BRAND_PINK);
  doc.setLineWidth(0.7);
  doc.line(centerX - 52, 23, centerX + 52, 23);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...BRAND_PURPLE);
  doc.text(reportTitle, centerX, 33, { align: 'center', maxWidth: pageWidth - 28 });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_TEXT);

  let y = 43;
  reportDetails.forEach(detail => {
    doc.text(detail, 14, y);
    y += 7;
  });

  return y + 2;
};

export const addReceiptHeader = (doc, title, details = []) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;
  const generatorName = getReportGeneratorName();
  const receiptDetails = [
    `Generated by: ${generatorName}`,
    ...details.filter(Boolean)
  ];

  doc.setFont('times', 'bolditalic');
  doc.setFontSize(24);
  doc.setTextColor(...BRAND_PINK);
  doc.text('Kaizen Mental Health Platform', centerX, 20, { align: 'center' });

  doc.setDrawColor(...BRAND_PINK);
  doc.setLineWidth(0.7);
  doc.line(centerX - 52, 25, centerX + 52, 25);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...BRAND_PURPLE);
  doc.text(title, centerX, 36, { align: 'center', maxWidth: pageWidth - 28 });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_TEXT);

  let y = 47;
  receiptDetails.forEach(detail => {
    doc.text(detail, 14, y);
    y += 7;
  });

  doc.setDrawColor(190, 190, 190);
  doc.setLineWidth(0.3);
  doc.line(14, y, pageWidth - 14, y);

  return y + 10;
};

export const addReceiptDetailsTable = (doc, sectionTitle, rows, startY) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.text(sectionTitle, 14, startY);

  doc.autoTable({
    startY: startY + 8,
    head: [['Field', 'Value']],
    body: rows,
    theme: 'striped',
    headStyles: { fillColor: BRAND_PINK, textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [246, 246, 246] },
    styles: { fontSize: 10, cellPadding: 3.5, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 52, fontStyle: 'bold', textColor: [55, 55, 55] },
      1: { cellWidth: 'auto', textColor: [35, 35, 35] }
    },
    margin: { left: 14, right: 14 }
  });

  return doc.lastAutoTable.finalY + 10;
};

export const addReceiptFooter = (doc, startY, note = 'This is a system-generated receipt.') => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const y = Math.min(startY, pageHeight - 30);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...MUTED_TEXT);
  doc.text('Thank you for choosing Kaizen Mental Health Platform.', 14, y);
  doc.text(note, 14, y + 6);
  doc.text(`Generated on ${new Date().toLocaleString()}`, 14, y + 12);
};
