const BRAND_PINK = [233, 30, 140];
const BRAND_PURPLE = [156, 39, 176];
const MUTED_TEXT = [100, 100, 100];

export const getReportGeneratorName = () => {
  const storedFullName = localStorage.getItem('fullName') || '';
  const firstName = localStorage.getItem('firstName') || '';
  const lastName = localStorage.getItem('lastName') || '';
  return storedFullName.trim() || `${firstName} ${lastName}`.trim() || 'User';
};

export const addReportHeader = (doc, title, details = []) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const centerX = pageWidth / 2;
  const generatorName = getReportGeneratorName();
  const reportTitle = !title.includes(` for ${generatorName}`)
    ? `${title} for ${generatorName}`
    : title;
  const reportDetails = [
    `Generated by: ${generatorName}`,
    ...details.filter(Boolean)
  ];

  doc.setFont('times', 'bolditalic');
  doc.setFontSize(24);
  doc.setTextColor(...BRAND_PINK);
  doc.text('Kaizen Mental Health Platform', centerX, 18, { align: 'center' });

  doc.setDrawColor(...BRAND_PINK);
  doc.setLineWidth(0.7);
  doc.line(centerX - 52, 23, centerX + 52, 23);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(...BRAND_PURPLE);
  doc.text(reportTitle, centerX, 33, { align: 'center', maxWidth: pageWidth - 28 });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED_TEXT);

  let y = 43;
  reportDetails.forEach(detail => {
    doc.text(detail, 14, y);
    y += 7;
  });

  return y + 2;
};
